# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: '난 버섯이 싫다'
description: '버섯은 친해지기가 어렵다'
permalink: pretty
logo: "/assets/logo.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "버섯이 싫은 글들"
